name: Run Python Script Daily

on:
  schedule:
    - cron: '05 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Run Python script
      run: python reference_and_tools/calendar_update.py  

    - name: Commit and push changes
      run: |
        git config --global user.email "wolfhenryyh@gmail.com"
        git config --global user.name "foxabbage"
        git add _pages/calendar.md
        git commit -m "_"
        git push origin main
